### ISSUE TITLE
AutoSite can't convert in/ to pages/

### ISSUE THREAD

**Issue by mariteaux** [dotcomboom/AutoSite#37]
RC3 throws an exception when trying to convert an older site automatically. Not sure if this is because I have the site in a Dropbox folder or something.

```
************** Exception Text **************
System.IO.IOException: Access to the path 'C:\Users\mariteaux\Dropbox\Web Shit\mariteaux\in' is denied.
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Microsoft.VisualBasic.FileIO.FileSystem.RenameDirectory(String directory, String newName)
   at AutoSite.Main.openSite(String path, Boolean autoload)
   at AutoSite.Main.browseForSite(Boolean n)
   at AutoSite.Main.OpenFolder_Click(Object sender, EventArgs e)
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.Control.WmCommand(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by dotcomboom** [comment]
Usually it's caused by something like the folder being open in an Explorer window. AutoSite now handles this exception by prompting to rename the folder manually.
