### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by dotcomboom** [dotcomboom/AutoSite#9]
Platform: Xubuntu 16.04 LTS
Python version: 3.5.2
Fresh install of AutoSite from pip.

```
~$ autosite
AUTOSITE

templates/default.html does not exist
Traceback (most recent call last):
  File "/home/eric/.local/bin/autosite", line 11, in <module>
    sys.exit(main())
  File "/home/eric/.local/lib/python3.5/site-packages/AutoSite/__init__.py", line 31, in main
    os.makedirs(os.path.dirname(template), exist_ok=True)
  File "/usr/lib/python3.5/posixpath.py", line 148, in dirname
    i = p.rfind(sep) + 1
AttributeError: 'PosixPath' object has no attribute 'rfind'
~$ 
```

**Workaround (source: https://github.com/le1nux/crawly/issues/2): Use Python >=3.6.1. I've tested it and it works, but I'll poke around for possible solutions for 3.5.**

**Comment by dotcomboom** [comment]
This appears to be an issue with `os.path.dirname()`. I'll replace it with another function that replicates it.

`os.path.dirname` is supposed to return `teje/templates` if the path is `teje/templates/default.html` (only as an example).

**Comment by dotcomboom** [comment]
Fixed in https://github.com/dotcomboom/AutoSite/commit/6c32b3d9dd1e5968d0d78f61fb25c102cfb3d669
